codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        informational: true
        if_ci_failed: error
    patch: off

component_management:
  individual_components:
    - component_id: core
      name: core
      paths:
        - "**"
        - "!ext/plt/platform_wayland.*"
        - "!lib/shitty/render_vk.*"
      statuses:
        - type: patch
          target: 80%
          threshold: 0%
          informational: false
          if_ci_failed: error
    - component_id: platform-wayland
      name: platform-wayland
      paths:
        - "ext/plt/platform_wayland.*"
    - component_id: renderer-vulkan
      name: renderer-vulkan
      paths:
        - "lib/shitty/render_vk.*"

comment:
  layout: "reach, diff, files, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

github_checks:
  annotations: true

ignore:
  - "tst/**/*"
  - "ext/libstd/**/*"
  - "**/*_ut.cpp"
  - "lib/shitty/test_mode.cpp"
  - "lib/shitty/test_mode.h"
  - "lib/shitty/test_input.cpp"
  - "lib/shitty/test_input.h"
