#!/usr/bin/env python3
"""Generate the InputKey name table for the chord parser.

Parses the InputKey enumeration out of plt/input.h and emits a header with
one {name, value} entry per enumerator, the name being the lowercased
enumerator spelling. input_remap.cpp builds its lookup maps from this
table, so every key plt can deliver is addressable in a -remap chord
without a hand-maintained list.

Usage: generate_input_keys.py PLT_INPUT_H OUTPUT_HEADER
"""

import re
import sys


def main():
    source, target = sys.argv[1], sys.argv[2]
    text = open(source).read()
    match = re.search(r"enum class InputKey : u8 \{(.*?)\};", text, re.S)
    if match is None:
        raise SystemExit("InputKey enum not found in " + source)
    names = re.findall(r"^\s*([A-Za-z0-9]+),?$", match.group(1), re.M)
    if "Count" not in names or len(names) < 32:
        raise SystemExit("InputKey enum parse looks wrong")
    names.remove("Count")

    out = open(target, "w")
    out.write("// Generated by generate_input_keys.py from plt/input.h; do not edit.\n")
    out.write("#pragma once\n\n")
    out.write("#include <plt/input.h>\n\n")
    out.write("struct InputKeyName {\n")
    out.write("    const char* name;\n")
    out.write("    plt::InputKey key;\n")
    out.write("};\n\n")
    out.write("static constexpr InputKeyName inputKeyNames[] = {\n")
    for name in names:
        out.write(f'    {{"{name.lower()}", plt::InputKey::{name}}},\n')
    out.write("};\n")
    out.close()


if __name__ == "__main__":
    main()
