#!/usr/bin/env python3
"""Emit the width-reclassification deltas between Unicode versions.

The terminal measures cells with current utf8proc tables; the shells at
the other end of the pty measure with whatever libc their system ships.
The only codepoints that can disagree between those two worlds are the
ones the consortium RECLASSIFIED - assigned long ago, moved between
Narrow and Wide later (the Unicode 9 emoji batch, the 15.1 trigrams).
Codepoints assigned after the older version keep their modern width:
an old libc answers nothing meaningful for them anyway, and rendering
new CJK or emoji at the wrong width would be strictly worse.

Reads the vendored UCD EastAsianWidth.txt files, writes a header with
the sorted delta ranges. Run by the build graph; the output is never
committed.

    unicode_width_deltas.py <unicode-dir> <out.h>
"""

import sys
from pathlib import Path

CODEPOINTS = 0x110000
VERSIONS = ("8.0.0", "15.0.0", "17.0.0")


def parse(path):
    assigned = bytearray(CODEPOINTS)
    wide = bytearray(CODEPOINTS)
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields, category = line.split(";")
        category = category.strip()
        if ".." in fields:
            first_text, last_text = fields.split("..")
        else:
            first_text = last_text = fields
        first = int(first_text, 16)
        last = int(last_text, 16)
        for codepoint in range(first, last + 1):
            assigned[codepoint] = 1
            wide[codepoint] = 1 if category in ("W", "F") else 0
    return assigned, wide


def ranges(member):
    result = []
    begin = None
    for codepoint in range(CODEPOINTS + 1):
        inside = codepoint < CODEPOINTS and member[codepoint]
        if inside and begin is None:
            begin = codepoint
        elif not inside and begin is not None:
            result.append((begin, codepoint - 1))
            begin = None
    return result


def reclassified(older_assigned, older_wide, newer_wide):
    gained = bytearray(CODEPOINTS)
    lost = bytearray(CODEPOINTS)
    for codepoint in range(CODEPOINTS):
        if not older_assigned[codepoint]:
            continue
        if newer_wide[codepoint] and not older_wide[codepoint]:
            gained[codepoint] = 1
        if older_wide[codepoint] and not newer_wide[codepoint]:
            lost[codepoint] = 1
    return ranges(gained), ranges(lost)


def emit(out, name, entries):
    out.append(f"inline constexpr WidthDeltaRange {name}[] = {{")
    for first, last in entries:
        out.append(f"    {{0x{first:04x}, 0x{last:04x}}},")
    out.append("};")
    out.append("")


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: unicode_width_deltas.py <unicode-dir> <out.h>")
    tables = {
        version: parse(Path(sys.argv[1]) / f"EastAsianWidth-{version}.txt")
        for version in VERSIONS
    }
    assigned8, wide8 = tables["8.0.0"]
    assigned15, wide15 = tables["15.0.0"]
    _, wide17 = tables["17.0.0"]
    wide_since9, narrow_since9 = reclassified(assigned8, wide8, wide15)
    wide_since16, narrow_since16 = reclassified(assigned15, wide15, wide17)
    if narrow_since9 or narrow_since16:
        # No Wide-to-Narrow reclassification has ever happened; the C++
        # side has no tables for one. If the consortium ever reverses a
        # width, this failure is the demand to handle it consciously.
        raise SystemExit(f"unexpected wide-to-narrow reclassification: {narrow_since9} {narrow_since16}")

    out = [
        "// Generated by unicode_width_deltas.py from the vendored UCD",
        "// EastAsianWidth.txt files; do not edit.",
        "#pragma once",
        "",
        "#include <std/sys/types.h>",
        "",
        "struct WidthDeltaRange {",
        "    u32 first;",
        "    u32 last;",
        "};",
        "",
        "// Wide today, Narrow before Unicode 9 (the emoji batch).",
    ]
    emit(out, "wideSince9", wide_since9)
    out.append("// Wide today, Narrow before Unicode 15.1 (the trigram batch).")
    emit(out, "wideSince16", wide_since16)
    Path(sys.argv[2]).write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
