#!/usr/bin/env python3
# Copyright (C) 2026 Shitty team
# MIT licensed
# See the file LICENSE.MIT for the full license.
#
# Reads the cmaps of the embedded fonts and emits their coverage as one
# sorted range table, a bitmask of faces per range. The embedded resolver
# answers cluster queries from this table without opening a face.

import struct
import sys
from pathlib import Path


def tables(data):
    count = struct.unpack_from(">H", data, 4)[0]
    result = {}
    for index in range(count):
        tag, _, offset, length = struct.unpack_from(">4sIII", data, 12 + 16 * index)
        result[tag] = (offset, length)
    return result


def cmap_codepoints(data):
    offset, _ = tables(data)[b"cmap"]
    count = struct.unpack_from(">HH", data, offset)[1]
    best = None
    for index in range(count):
        platform, encoding, subtable = struct.unpack_from(
            ">HHI", data, offset + 4 + 8 * index
        )
        fmt = struct.unpack_from(">H", data, offset + subtable)[0]
        if fmt in (4, 12):
            # Prefer the widest table; format 12 covers the planes.
            if best is None or fmt > best[0]:
                best = (fmt, offset + subtable)
    if best is None:
        raise SystemExit("no usable cmap subtable")
    fmt, at = best
    covered = set()
    if fmt == 4:
        seg_x2 = struct.unpack_from(">H", data, at + 6)[0]
        segments = seg_x2 // 2
        ends = struct.unpack_from(f">{segments}H", data, at + 14)
        starts = struct.unpack_from(f">{segments}H", data, at + 16 + seg_x2)
        for start, end in zip(starts, ends):
            if start == 0xFFFF:
                continue
            covered.update(range(start, end + 1))
    else:
        groups = struct.unpack_from(">I", data, at + 12)[0]
        for index in range(groups):
            start, end, _ = struct.unpack_from(">III", data, at + 16 + 12 * index)
            covered.update(range(start, end + 1))
    return covered


def main():
    if len(sys.argv) < 3:
        raise SystemExit(
            "usage: generate_font_coverage.py OUTPUT FONT [FONT ...]"
        )
    output = Path(sys.argv[1])
    masks = {}
    for bit, path in enumerate(sys.argv[2:]):
        for codepoint in cmap_codepoints(Path(path).read_bytes()):
            masks[codepoint] = masks.get(codepoint, 0) | (1 << bit)

    ranges = []
    for codepoint in sorted(masks):
        mask = masks[codepoint]
        if ranges and ranges[-1][1] + 1 == codepoint and ranges[-1][2] == mask:
            ranges[-1][1] = codepoint
        else:
            ranges.append([codepoint, codepoint, mask])

    lines = [
        "// Generated by generate_font_coverage.py; do not edit.",
        "#pragma once",
        "",
        "#include <std/sys/types.h>",
        "",
        "struct EmbeddedCoverageRange {",
        "    u32 first;",
        "    u32 last;",
        "    u8 faces;",
        "};",
        "",
        "inline constexpr EmbeddedCoverageRange embeddedCoverageRanges[] = {",
    ]
    for first, last, mask in ranges:
        lines.append(f"    {{0x{first:x}, 0x{last:x}, 0x{mask:x}}},")
    lines.append("};")
    lines.append("")
    output.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
