#!/usr/bin/env python3


def command(columns, rows, script):
    return {
        "columns": columns,
        "rows": rows,
        "command": script,
        "checkpoint": "exit",
        "actions": (),
    }


def session(
    columns, rows, script, *actions, minimum=1, cleanup=None,
    expect=(), min_colors=0,
):
    return {
        "columns": columns,
        "rows": rows,
        "command": script,
        "checkpoint": "quiet",
        "actions": actions,
        "minimum": minimum,
        "cleanup": cleanup,
        "expected_text": expect,
        "minimum_color_styles": min_colors,
    }


def shell(columns, rows, *actions):
    return {
        "columns": columns,
        "rows": rows,
        "command": None,
        "checkpoint": "exit",
        "actions": actions,
    }


def transcript(columns, rows, script, *actions):
    return {
        "columns": columns,
        "rows": rows,
        "command": script,
        "checkpoint": "action_exit",
        "actions": actions,
    }


def key(name, modifiers=0):
    return ("key", name, modifiers)


SCENARIOS = {
    "ls_color_columns": command(80, 24, "ls --color=always -CF ."),
    "ls_color_long": command(120, 24, "ls --color=always -la ."),
    "ls_recursive": command(80, 35, "ls --color=always -lR ."),
    "ls_quote_names": command(120, 12, "ls --color=always -lb ."),
    "ls_inode_blocks": command(120, 24, "ls --color=always -lis ."),
    "eza_columns": command(80, 24, "eza --color=always --icons=never ."),
    "eza_long": command(120, 24, "eza --color=always --icons=never -la ."),
    "eza_tree": command(120, 35, "eza --color=always --icons=never --tree --level=3 ."),
    "eza_sort_size": command(80, 24, "eza --color=always --icons=never -l --sort=size ."),
    "tree_color": command(80, 24, "tree -a -C ."),
    "tree_ascii": command(120, 24, "tree -a --charset ascii ."),
    "tree_dirs": command(80, 12, "tree -d -C ."),
    "bat_python": command(120, 35, "bat --color=always --paging=never --style=numbers,grid sample.py"),
    "bat_json": command(80, 24, "bat --color=always --paging=never --style=header,grid data.json"),
    "bat_unicode": command(40, 12, "bat --color=always --paging=never --style=plain unicode.txt"),
    "coreutils_stat": command(120, 24, "stat sample.py unicode.txt"),
    "coreutils_wc": command(80, 12, "wc -lwc sample.py unicode.txt data.json"),
    "coreutils_od": command(120, 24, "od -A x -t x1z -N 128 binary.dat"),
    "coreutils_sort": command(80, 12, "LC_ALL=C sort words.txt | uniq -c"),
    "coreutils_sha256": command(120, 12, "sha256sum sample.py unicode.txt data.json"),
    "find_tree": command(80, 24, "find . -maxdepth 3 -print | LC_ALL=C sort"),
    "find_types": command(120, 24, "find . -maxdepth 3 -printf '%y %p\\n' | LC_ALL=C sort"),
    "du_human": command(80, 24, "du -ah . | LC_ALL=C sort"),
    "grep_color": command(80, 12, "grep --color=always -nE 'return|print|str' sample.py"),
    "grep_recursive": command(120, 24, "grep --color=always -RIn 'one\\|hello' ."),
    "head_tail": command(80, 24, "head -n 3 unicode.txt; printf '%s\\n' '---'; tail -n 3 unicode.txt"),
    "nl_unicode": command(40, 12, "nl -ba unicode.txt"),
    "fold_long": command(40, 12, "fold -w 17 long.txt"),
    "cut_table": command(80, 12, "cut -f 1,3 table.tsv"),
    "paste_columns": command(80, 12, "paste words.txt unicode.txt"),
    "sed_transform": command(80, 12, "sed -n 's/[aeiou]/_/g;=' words.txt"),
    "awk_table": command(80, 12, "awk -F '\\t' '{printf \"%02d | %-10s | %s\\n\", NR, $1, $3}' table.tsv"),
    "diff_color": command(120, 24, "diff --color=always -u before.txt after.txt || test $? = 1"),
    "printf_tabs": command(40, 12, "printf 'a\\tb\\tc\\n1234567\\tX\\n\\tindented\\n'"),
    "printf_controls": command(80, 12, "printf '\\e[2J\\e[Htop\\e[4;12Hplaced\\e[2A\\e[5Ccursor\\n'"),
    "printf_truecolor": command(80, 12, "python3 color_grid.py"),
    "bash_commands": shell(
        80, 24,
        b"printf 'plain %s\\n' text\nprintf '\\e[1;34mbold-blue\\e[0m\\n'\nexit\n",
    ),
    "bash_unicode": shell(
        40, 12,
        "printf 'λ界 é 👩🏽‍💻\\n'\nprintf '%*s\\n' 30 done\nexit\n".encode(),
    ),
    "bash_listing": shell(
        120, 24,
        b"ls --color=always -la\nprintf '\\e[3;4;58;5;202mstyled\\e[0m\\n'\nexit\n",
    ),
    "bash_scrollback": shell(
        80, 24,
        b"for i in $(seq 1 80); do printf 'history %03d abcdefghijklmnopqrstuvwxyz\\n' $i; done\nexit\n",
    ),
    "bash_multiline": shell(
        80, 24,
        b"for word in alpha beta gamma; do\nprintf '<%s>\\n' \"$word\"\ndone\nexit\n",
    ),
    "bash_backspace": shell(
        40, 12,
        b"printf 'abcdef\\b\\bXY\\n'\nprintf 'overwrite\\rnew\\n'\nexit\n",
    ),
    "bash_sgr_matrix": shell(
        120, 24,
        b"for n in 1 2 3 4 5 7 8 9; do printf '\\e[%smSGR-%s\\e[0m ' $n $n; done; printf '\\n'\nexit\n",
    ),
    "bash_256_colors": shell(
        120, 24,
        b"for n in 16 17 18 19 20 21 46 82 118 154 190 226; do printf '\\e[48;5;%sm %3s \\e[0m' $n $n; done; printf '\\n'\nexit\n",
    ),
    "bash_truecolor": shell(
        80, 24,
        b"for rgb in '255;0;0' '0;255;0' '0;0;255' '250;128;10'; do printf '\\e[38;2;%sm%s\\e[0m ' $rgb $rgb; done; printf '\\n'\nexit\n",
    ),
    "less_top": session(80, 24, "exec less -R unicode.txt"),
    "less_page_down": session(80, 24, "exec less -R long.txt", b" "),
    "less_search": session(80, 24, "exec less -R long.txt", b"/line 047\n"),
    "less_end": session(80, 24, "exec less -R long.txt", b"G"),
    "less_numbers": session(120, 35, "exec less -N -R sample.py", b"G"),
    "less_horizontal": session(40, 12, "exec less -S long_lines.txt", b"\x1b[C\x1b[C\x1b[C"),
    "less_ansi": session(80, 24, "exec less -R ansi.txt", b"G"),
    "less_help": session(80, 24, "exec less long.txt", b"h"),
    "mc_initial": session(80, 24, "exec mc -u", minimum=1000),
    "mc_move": session(80, 24, "exec mc -u", b"\x1b[B\x1b[B\x1b[B", minimum=1000),
    "mc_other_panel": session(120, 35, "exec mc -u", b"\t\x1b[B\x1b[B", minimum=1000),
    "mc_quick_view": session(80, 24, "exec mc -u", b"\x1b[15~", minimum=1000),
    "mc_tree": session(120, 35, "exec mc -u", b"\x1b[17~", minimum=1000),
    "mc_hidden": session(80, 24, "exec mc -u", b"\x1b[19~", minimum=1000),
    "htop_initial": session(80, 24, "exec htop -d 10", minimum=1000),
    "htop_wide": session(120, 35, "exec htop -d 10", minimum=1000),
    "htop_tree": session(120, 35, "exec htop -d 10", b"t", minimum=1000),
    "htop_threads": session(80, 24, "exec htop -d 10", b"H", minimum=1000),
    "htop_sort_memory": session(80, 24, "exec htop -d 10", b"M", minimum=1000),
    "htop_scroll": session(40, 12, "exec htop -d 10", b"\x1b[B\x1b[B\x1b[C", minimum=1000),
    "vim_initial_python": session(80, 24, "exec vim -Nu NONE -n sample.py", minimum=1000),
    "vim_initial_unicode": session(40, 12, "exec vim -Nu NONE -n unicode.txt", minimum=1000),
    "vim_numbers": session(80, 24, "exec vim -Nu NONE -n sample.py", b":set number\r", minimum=1000),
    "vim_relative_numbers": session(120, 35, "exec vim -Nu NONE -n long.txt", b":set number relativenumber\r", minimum=1000),
    "vim_syntax_python": session(120, 35, "exec vim -Nu NONE -n sample.py", b":syntax on\r", minimum=1000),
    "vim_search": session(80, 24, "exec vim -Nu NONE -n sample.py", b"/return\r", minimum=1000),
    "vim_search_unicode": session(80, 24, "exec vim -Nu NONE -n unicode.txt", " /界\r".lstrip().encode(), minimum=1000),
    "vim_search_count": session(80, 24, "exec vim -Nu NONE -n long.txt", b"/line 047\rnn", minimum=1000),
    "vim_end_of_file": session(80, 24, "exec vim -Nu NONE -n long.txt", b"G", minimum=1000),
    "vim_center_cursor": session(80, 24, "exec vim -Nu NONE -n long.txt", b"50Gzz", minimum=1000),
    "vim_insert_ascii": session(80, 24, "exec vim -Nu NONE -n sample.py", b"Goadded from trace\x1b", minimum=1000),
    "vim_insert_unicode": session(80, 24, "exec vim -Nu NONE -n unicode.txt", "Goλ界 👩🏽‍💻\x1b".encode(), minimum=1000),
    "vim_substitute": session(120, 24, "exec vim -Nu NONE -n sample.py", b":%s/name/subject/g\r", minimum=1000),
    "vim_visual_lines": session(80, 24, "exec vim -Nu NONE -n sample.py", b"ggVjj", minimum=1000),
    "vim_visual_block": session(80, 24, "exec vim -Nu NONE -n sample.py", b"gg\x16jjll", minimum=1000),
    "vim_split": session(120, 35, "exec vim -Nu NONE -n sample.py", b":split unicode.txt\r", minimum=1000),
    "vim_vsplit": session(120, 35, "exec vim -Nu NONE -n sample.py", b":vsplit data.json\r", minimum=1000),
    "vim_cursorline": session(80, 24, "exec vim -Nu NONE -n sample.py", b":set cursorline\rjj", minimum=1000),
    "vim_listchars": session(80, 24, "exec vim -Nu NONE -n table.tsv", b":set list\r", minimum=1000),
    "vim_wrap_long": session(40, 12, "exec vim -Nu NONE -n long_lines.txt", b":set wrap\r", minimum=1000),
    "vim_nowrap_long": session(40, 12, "exec vim -Nu NONE -n long_lines.txt", b":set nowrap\r10l", minimum=1000),
    "vim_command_history": session(80, 24, "exec vim -Nu NONE -n sample.py", b":set number\r:set list\r:q:\r", minimum=1000),
    "vim_help": session(120, 35, "exec vim -Nu NONE -n sample.py", b":help motion.txt\r", minimum=1000),
    "vim_status_ruler": session(80, 24, "exec vim -Nu NONE -n sample.py", b":set ruler showcmd\r10G5l", minimum=1000),
    "nano_initial": session(80, 24, "exec nano --ignorercfiles sample.py", minimum=100),
    "nano_narrow": session(40, 12, "exec nano --ignorercfiles unicode.txt", minimum=100),
    "nano_move": session(80, 24, "exec nano --ignorercfiles sample.py", b"\x1b[B\x1b[B\x1b[C\x1b[C", minimum=100),
    "nano_search": session(80, 24, "exec nano --ignorercfiles sample.py", b"\x17return\r", minimum=100),
    "nano_search_unicode": session(80, 24, "exec nano --ignorercfiles unicode.txt", "\x17界\r".encode(), minimum=100),
    "nano_insert": session(80, 24, "exec nano --ignorercfiles sample.py", b"\x1b[B\x05 # trace", minimum=100),
    "nano_help": session(120, 35, "exec nano --ignorercfiles sample.py", b"\x07", minimum=100),
    "nano_whereis_cancel": session(80, 24, "exec nano --ignorercfiles sample.py", b"\x17missing\x03", minimum=100),
    "nano_mark": session(80, 24, "exec nano --ignorercfiles sample.py", b"\x1b[A\x00\x1b[B\x1b[B", minimum=100),
    "nano_end": session(80, 24, "exec nano --ignorercfiles long.txt", b"\x1b/", minimum=100),
    "ed_print": transcript(80, 24, "exec ed sample.py", b"1,$p\nq\n"),
    "ed_numbered": transcript(80, 24, "exec ed sample.py", b"1,$n\nq\n"),
    "ed_search": transcript(80, 24, "exec ed sample.py", b"/return/p\nq\n"),
    "ed_substitute": transcript(80, 24, "exec ed sample.py", b"1,$s/name/value/g\n1,$p\nw\nq\n"),
    "ed_append": transcript(40, 12, "exec ed unicode.txt", "a\nλ界 extra\n.\n$p\nw\nq\n".encode()),
    "ed_list": transcript(80, 24, "exec ed table.tsv", b"1,$l\nq\n"),
    "ed_join": transcript(80, 12, "exec ed before.txt", b"1,2j\n1,$p\nw\nq\n"),
    "ed_marks": transcript(80, 12, "exec ed before.txt", b"2ka\n'ap\nq\n"),
    "zsh_basic": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"print hello\n", minimum=20),
    "zsh_unicode": session(40, 12, "export PS1='zsh% '; exec zsh -f", "print 'λ界 👩🏽‍💻'\n".encode(), minimum=20),
    "zsh_sgr": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"print -P '%B%F{33}zsh color%f%b'\n", minimum=20),
    "zsh_glob": session(120, 24, "export PS1='zsh% '; exec zsh -f", b"print -l **/*(.)\n", minimum=20),
    "zsh_loop": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"for x in alpha beta gamma; do print -r -- \"<$x>\"; done\n", minimum=20),
    "zsh_array": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"a=(one two 'three four'); print -l $a\n", minimum=20),
    "zsh_multiline": session(80, 24, "export PS1='zsh% '; export PS2='more> '; exec zsh -f", b"for x in one two; do\nprint $x\ndone\n", minimum=20),
    "zsh_error": session(80, 12, "export PS1='zsh% '; exec zsh -f", b"command_that_does_not_exist\n", minimum=20),
    "zsh_history": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"print first\nprint second\n\x1b[A", minimum=20),
    "zsh_completion": session(120, 24, "export PS1='zsh% '; exec zsh -f", b"autoload -Uz compinit; compinit -u\nprint -\t", minimum=20),
    "zsh_256_colors": session(120, 24, "export PS1='zsh% '; exec zsh -f", b"for n in {16..27}; do print -n -- $'\\e[48;5;'$n'm  '$n'  \\e[0m'; done; print\n", minimum=20),
    "zsh_scrollback": session(80, 24, "export PS1='zsh% '; exec zsh -f", b"repeat 70 print zsh-history-line\n", minimum=20),
    "fish_basic": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"echo hello\n", minimum=20),
    "fish_unicode": session(40, 12, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", "echo 'λ界 👩🏽‍💻'\n".encode(), minimum=20),
    "fish_sgr": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"set_color --bold blue; echo fish-color; set_color normal\n", minimum=20),
    "fish_glob": session(120, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"printf '%s\\n' **\n", minimum=20),
    "fish_loop": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"for x in alpha beta gamma; echo '<'$x'>'; end\n", minimum=20),
    "fish_list": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"set a one two 'three four'; printf '[%s]\\n' $a\n", minimum=20),
    "fish_multiline": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"for x in one two\necho $x\nend\n", minimum=20),
    "fish_error": session(80, 12, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"command_that_does_not_exist\n", minimum=20),
    "fish_history": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"echo first\necho second\n\x1b[A", minimum=20),
    "fish_completion": session(120, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"printf --\t", minimum=20),
    "fish_256_colors": session(120, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"for n in (seq 16 27); printf '\\e[48;5;%sm %3s \\e[0m' $n $n; end; echo\n", minimum=20),
    "fish_scrollback": session(80, 24, "exec fish --no-config -C \"function fish_prompt; printf 'fish> '; end\"", b"for n in (seq 1 70); printf 'fish-history-%03d\\n' $n; end\n", minimum=20),
    "fzf_initial": session(80, 24, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse", minimum=300),
    "fzf_query": session(80, 24, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse", b"047", minimum=300),
    "fzf_move": session(80, 24, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse", b"\x1b[B\x1b[B\x1b[B", minimum=300),
    "fzf_reverse": session(80, 24, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse --layout=reverse", b"item-09", minimum=300),
    "fzf_border": session(120, 35, "seq -f 'entry-%03g' 1 200 | exec fzf --no-mouse --border --info=inline", b"entry-1", minimum=300),
    "fzf_multi": session(80, 24, "seq -f 'choice-%03g' 1 60 | exec fzf --no-mouse --multi", b"\t\x1b[B\t\x1b[B", minimum=300),
    "fzf_ansi": session(80, 24, "python3 color_items.py | exec fzf --ansi --no-mouse", b"blue", minimum=300),
    "fzf_preview": session(120, 35, "seq -f 'file-%03g' 1 40 | exec fzf --no-mouse --preview='printf \\\"preview for %s\\\\nline two\\\\nλ界\\\\n\\\" {}'", b"\x1b[B\x1b[B", minimum=300),
    "dialog_msgbox": session(80, 24, "exec dialog --no-shadow --title 'Trace message' --msgbox 'Hello from dialog.\\nSecond line: λ界.' 10 50", minimum=300),
    "dialog_yesno": session(80, 24, "exec dialog --no-shadow --title 'Question' --yesno 'Keep this deterministic trace?' 9 46", b"\t", minimum=300),
    "dialog_menu": session(80, 24, "exec dialog --no-shadow --title 'Menu' --menu 'Choose item' 15 52 6 a Alpha b Beta c Gamma d Delta e Epsilon", b"c", minimum=300),
    "dialog_checklist": session(120, 35, "exec dialog --no-shadow --title 'Checklist' --checklist 'Features' 17 60 8 a Alpha on b Beta off c Gamma on d Delta off", b" ", minimum=300),
    "dialog_radiolist": session(80, 24, "exec dialog --no-shadow --title 'Radio' --radiolist 'Select one' 15 52 6 a Alpha on b Beta off c Gamma off", b"b ", minimum=300),
    "dialog_inputbox": session(80, 24, "exec dialog --no-shadow --title 'Input' --inputbox 'Value:' 10 50 'initial'", b"-edited", minimum=300),
    "dialog_password": session(80, 24, "exec dialog --no-shadow --title 'Secret' --passwordbox 'Password:' 10 50", b"not-a-secret", minimum=300),
    "dialog_textbox": session(120, 35, "exec dialog --no-shadow --title 'Text' --textbox long.txt 28 100", b"jj", minimum=300),
    "sqlite_box": command(80, 24, "sqlite3 -box ':memory:' \"with t(id,name) as (values(1,'alpha'),(2,'βeta'),(3,'界')) select * from t;\""),
    "sqlite_column": command(80, 24, "sqlite3 -column -header ':memory:' \"select 1 as id, 'alpha' as name union all select 22, 'longer value';\""),
    "sqlite_table": command(80, 24, "sqlite3 -table ':memory:' \"select 'left' as side, 10 as amount union all select 'right', 200;\""),
    "sqlite_markdown": command(80, 24, "sqlite3 -markdown ':memory:' \"select 'λ' as greek, '界' as wide union all select 'beta','日本語';\""),
    "sqlite_json": command(120, 24, "sqlite3 -json ':memory:' \"select 1 as id, 'alpha' as name union all select 2, '界';\""),
    "sqlite_quote": command(120, 24, "sqlite3 -quote ':memory:' \"select null, 42, 3.5, 'a''b', x'00ff';\""),
    "sqlite_explain": command(120, 35, "sqlite3 ':memory:' \"create table t(a integer primary key,b text); explain select b from t where a=4;\""),
    "sqlite_recursive": command(80, 24, "sqlite3 -box ':memory:' \"with recursive n(x) as (values(1) union all select x+1 from n where x<12) select x, printf('%.*c',x,'*') as bar from n;\""),
    "git_log_oneline": command(120, 24, "git --no-pager log --color=always --oneline --decorate --all"),
    "git_log_graph": command(120, 35, "git --no-pager log --color=always --graph --oneline --decorate --all"),
    "git_show": command(120, 35, "git --no-pager show --color=always --stat --oneline HEAD"),
    "git_diff": command(120, 35, "printf 'working tree\\n' >> before.txt; git --no-pager diff --color=always"),
    "git_status": command(80, 24, "printf 'untracked\\n' > new-file; git status --short --branch"),
    "git_branch": command(80, 24, "git branch --color=always -avv"),
    "git_tag": command(80, 24, "git tag -n --color=always"),
    "git_log_format": command(120, 24, "git --no-pager log --color=always --format='%C(yellow)%h%Creset %C(cyan)%ad%Creset %s' --date=short"),
    "tig_initial": session(120, 35, "exec tig --all", minimum=100),
    "tig_main_narrow": session(80, 24, "exec tig --all", minimum=100),
    "tig_move": session(120, 35, "exec tig --all", b"jjj", minimum=100),
    "tig_diff": session(120, 35, "exec tig --all", b"\r", minimum=100),
    "tig_log_view": session(120, 35, "exec tig log", b"jj", minimum=100),
    "tig_status": session(80, 24, "printf 'working\\n' >> before.txt; exec tig status", minimum=100),
    "tig_help": session(120, 35, "exec tig --all", b"h", minimum=100),
    "tig_search": session(120, 35, "exec tig --all", b"/second\r", minimum=100),
    "micro_initial": session(80, 24, "exec micro -filetype python sample.py", minimum=100),
    "micro_narrow": session(40, 12, "exec micro -config-dir $HOME/.config/micro unicode.txt", minimum=100),
    "micro_move": session(80, 24, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x1b[B\x1b[B\x1b[C\x1b[C", minimum=100),
    "micro_search": session(80, 24, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x06return\r", minimum=100),
    "micro_insert": session(80, 24, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x1b[B\x1b[F # trace", minimum=100),
    "micro_select": session(80, 24, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x1b[1;2B\x1b[1;2B", minimum=100),
    "micro_help": session(120, 35, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x07", minimum=100),
    "micro_command": session(80, 24, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x05set ruler true\r", minimum=100),
    "micro_split": session(120, 35, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x05vsplit data.json\r", minimum=100),
    "micro_tab": session(120, 35, "exec micro -config-dir $HOME/.config/micro sample.py", b"\x05tab unicode.txt\r", minimum=100),
    "micro_end": session(80, 24, "exec micro -config-dir $HOME/.config/micro long.txt", b"\x1b[F", minimum=100),
    "micro_unicode": session(80, 24, "exec micro -config-dir $HOME/.config/micro unicode.txt", "\x1b[Bλ界 👩🏽‍💻".encode(), minimum=100),
    "kak_initial": session(80, 24, "exec kak -n sample.py", minimum=1000),
    "kak_narrow": session(40, 12, "exec kak -n unicode.txt", minimum=500),
    "kak_move": session(80, 24, "exec kak -n sample.py", b"jjll", minimum=1000),
    "kak_search": session(80, 24, "exec kak -n sample.py", b"/return\r", minimum=1000),
    "kak_insert": session(80, 24, "exec kak -n sample.py", b"iadded from trace\x1b", minimum=1000),
    "kak_select_lines": session(80, 24, "exec kak -n sample.py", b"xjj", minimum=1000),
    "kak_split": session(120, 35, "exec kak -n sample.py", b":edit -existing unicode.txt\r", minimum=1000),
    "kak_numbers": session(80, 24, "exec kak -n sample.py", b":add-highlighter global/ number-lines\r", minimum=1000),
    "kak_echo_version": session(120, 35, "exec kak -n sample.py", b":echo %val{version}\r", minimum=1000),
    "kak_unicode": session(80, 24, "exec kak -n unicode.txt", "iλ界 👩🏽‍💻\x1b".encode(), minimum=1000),
    "dte_initial": session(80, 24, "exec dte -c 'set no-save-on-exit true' sample.py", minimum=500),
    "dte_narrow": session(40, 12, "exec dte -c 'set no-save-on-exit true' unicode.txt", minimum=300),
    "dte_move": session(80, 24, "exec dte -c 'set no-save-on-exit true' sample.py", b"\x1b[B\x1b[B\x1b[C", minimum=500),
    "dte_search": session(80, 24, "exec dte -c 'set no-save-on-exit true' sample.py", b"\x06return\r", minimum=500),
    "dte_insert": session(80, 24, "exec dte -c 'set no-save-on-exit true' sample.py", b"\x1b[Btrace", minimum=500),
    "dte_line_numbers": session(80, 24, "exec dte -c 'set no-save-on-exit true' -c 'set display-line-numbers true' sample.py", minimum=500),
    "dte_unicode": session(80, 24, "exec dte -c 'set no-save-on-exit true' unicode.txt", "\x1b[Bλ界".encode(), minimum=500),
    "dte_long": session(120, 35, "exec dte -c 'set no-save-on-exit true' long.txt", b"\x1b[6~\x1b[6~", minimum=500),
    "nnn_initial": session(80, 24, "exec nnn", minimum=500),
    "nnn_detail": session(120, 35, "exec nnn -d", minimum=500),
    "nnn_move": session(80, 24, "exec nnn", b"jjj", minimum=500),
    "nnn_hidden": session(80, 24, "exec nnn", b".", minimum=500),
    "nnn_filter": session(80, 24, "exec nnn", b"/sample\r", minimum=500),
    "nnn_context": session(120, 35, "exec nnn", b"2", minimum=500),
    "nnn_sort": session(80, 24, "exec nnn", b"t", minimum=500),
    "nnn_help": session(120, 35, "exec nnn", b"?", minimum=500),
    "vifm_initial": session(80, 24, "exec vifm --no-configs . .", minimum=1000),
    "vifm_wide": session(120, 35, "exec vifm --no-configs . .", minimum=1000),
    "vifm_move": session(80, 24, "exec vifm --no-configs . .", b"jjj", minimum=1000),
    "vifm_other_panel": session(120, 35, "exec vifm --no-configs . .", b"\tjj", minimum=1000),
    "vifm_hidden": session(80, 24, "exec vifm --no-configs . .", b"zh", minimum=1000),
    "vifm_sort": session(80, 24, "exec vifm --no-configs . .", b"s", minimum=1000),
    "vifm_visual": session(80, 24, "exec vifm --no-configs . .", b"Vjj", minimum=1000),
    "vifm_help": session(120, 35, "exec vifm --no-configs . .", b"h", minimum=1000),
    "lf_initial": session(80, 24, "exec lf", minimum=500),
    "lf_wide": session(120, 35, "exec lf", minimum=500),
    "lf_move": session(80, 24, "exec lf", b"jjj", minimum=500),
    "lf_hidden": session(80, 24, "exec lf", b"zh", minimum=500),
    "lf_filter": session(80, 24, "exec lf", b"f", minimum=500),
    "lf_preview": session(120, 35, "exec lf", b"js", minimum=500),
    "lf_command": session(80, 24, "exec lf", b":set number\r", minimum=500),
    "lf_marks": session(80, 24, "exec lf", b"madd\r", minimum=500),
    "vim_diff": session(120, 35, "exec vim -Nu NONE -n -d before.txt after.txt", minimum=1000),
    "vim_tabs": session(120, 35, "exec vim -Nu NONE -n sample.py", b":tabedit unicode.txt\r", minimum=1000),
    "less_status": session(80, 24, "exec less -R long.txt", b"="),
    "less_mark_roundtrip": session(80, 24, "exec less -R long.txt", b"maG'a"),
    "fzf_height": session(120, 35, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse --height=60% --border", b"047", minimum=300),
    "fzf_header": session(80, 24, "seq -f 'item-%03g' 1 100 | exec fzf --no-mouse --header='real application trace'", b"item-09", minimum=300),
    "dialog_calendar": session(80, 24, "exec dialog --no-shadow --title 'Calendar' --calendar 'Choose date' 0 0 02 01 2020", minimum=300),
    "dialog_form": session(120, 35, "exec dialog --no-shadow --title 'Form' --form 'Deterministic values' 16 70 6 'Name:' 1 1 'trace' 1 20 30 40 'Number:' 3 1 '42' 3 20 10 10", minimum=300),
    "btop_initial": session(80, 24, "exec btop --force-utf", minimum=1000),
    "btop_wide": session(120, 35, "exec btop --force-utf", minimum=1000),
    "btop_process": session(80, 24, "exec btop --force-utf", b"p", minimum=1000),
    "btop_move": session(120, 35, "exec btop --force-utf", b"jjj", minimum=1000),
    "btop_menu": session(120, 35, "exec btop --force-utf", b"m", minimum=1000),
    "btop_help": session(120, 35, "exec btop --force-utf", b"h", minimum=1000),
    "tmux_initial": session(80, 24, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_wide": session(120, 35, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_new_window": session(80, 24, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"\x02c", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_split_horizontal": session(120, 35, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"\x02%", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_split_vertical": session(120, 35, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"\x02\"", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_command": session(80, 24, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"\x02:display-message 'trace message'\r", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_copy_mode": session(80, 24, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"printf 'one\\ntwo\\nthree\\n'\r\x02[", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "tmux_help": session(120, 35, "export PS1='tmux$ '; exec tmux -L trace -f /dev/null new-session -s main", b"\x02?", minimum=1000, cleanup=("tmux", "-L", "trace", "kill-server")),
    "fastfetch_default": command(120, 35, "fastfetch --pipe false"),
    "fastfetch_small": command(80, 24, "fastfetch --pipe false --logo none"),
    "fastfetch_structure": command(120, 24, "fastfetch --pipe false --logo none --structure 'OS:Kernel:Uptime:Shell:Terminal:CPU:Memory'"),
    "fastfetch_colors": command(80, 24, "fastfetch --pipe false --logo small"),
    "most_long": session(80, 24, "exec most long.txt", b" ", minimum=500),
    "lazygit_initial": session(120, 35, "exec lazygit", minimum=1000),
    "atop_initial": session(120, 35, "exec atop 10", minimum=1000),
    "clifm_initial": session(80, 24, "exec clifm", minimum=500),
    "lazygit_help": session(
        120, 35, "exec lazygit", b"?", minimum=1000,
        expect=("Keybindings", "Stage lines", "Discard"), min_colors=5,
    ),
    "vim_syntax_c": session(
        120, 35, "exec vim -Nu NONE -n src/main.c", b":syntax on\r",
        minimum=1000, expect=("#include", "puts"), min_colors=4,
    ),
    "vim_syntax_json": session(
        80, 24, "exec vim -Nu NONE -n data.json", b":syntax on\r",
        minimum=1000, expect=('"enabled"', '"items"'), min_colors=4,
    ),
    "vim_syntax_markdown": session(
        80, 24, "exec vim -Nu NONE -n src/nested/notes.md", b":syntax on\r",
        minimum=1000, expect=("# Notes", "- one"), min_colors=3,
    ),
    "vim_colorscheme_completion": session(
        120, 35, "exec vim -Nu NONE -n sample.py",
        b":syntax on\r:colorscheme \t", minimum=1000,
        expect=("blue", "default"), min_colors=3,
    ),
    "vim_insert_completion": session(
        120, 35, "exec vim -Nu NONE -n sample.py", b":syntax on\rGopri\x0e",
        minimum=1000, expect=("print",),
        min_colors=3,
    ),
    "vim_buffer_list": session(
        120, 35, "exec vim -Nu NONE -n sample.py",
        b":edit unicode.txt\r:edit data.json\r:buffers\r",
        minimum=1000, expect=("sample.py", "unicode.txt", "data.json"),
        min_colors=2,
    ),
    "vim_registers": session(
        120, 35, "exec vim -Nu NONE -n sample.py", b"yy:registers\r",
        minimum=1000, expect=("Type Name Content", "#!/usr/bin/env python3"),
        min_colors=2,
    ),
    "vim_wildmenu_edit": session(
        120, 35, "exec vim -Nu NONE -n sample.py",
        b":set wildmenu\r:edit s\t", minimum=1000,
        expect=("sample.py", "src/"), min_colors=2,
    ),
    "nano_syntax_python": session(
        80, 24, "exec nano --syntax=python sample.py", minimum=100,
        expect=("def greet", "return f"), min_colors=3,
    ),
    "nano_syntax_c": session(
        80, 24, "exec nano --syntax=c src/main.c", minimum=100,
        expect=("#include", "puts"), min_colors=3,
    ),
    "nano_replace_prompt": session(
        80, 24, "exec nano --ignorercfiles sample.py", b"\x1c",
        minimum=100, expect=("Search (to replace)",), min_colors=1,
    ),
    "nano_file_browser": session(
        120, 35, "exec nano --ignorercfiles sample.py", b"\x12", b"\x14",
        minimum=100, expect=("DIR:", "sample.py"), min_colors=1,
    ),
    "kak_syntax_python": session(
        80, 24, "exec kak -n sample.py",
        b":add-highlighter window/ regex '\\b(def|for|return|in)\\b' 0:magenta\r",
        minimum=500, expect=("def greet", "return f"), min_colors=5,
    ),
    "kak_syntax_c": session(
        120, 35, "exec kak -n src/main.c",
        b":add-highlighter window/ regex '\\b(int|void|return)\\b' 0:magenta\r",
        minimum=500, expect=("#include", "puts"), min_colors=5,
    ),
    "kak_syntax_json": session(
        80, 24, "exec kak -n data.json",
        b":add-highlighter window/ regex '\"[^\"]+\"' 0:magenta\r",
        minimum=500, expect=('"enabled"', '"items"'), min_colors=5,
    ),
    "kak_syntax_markdown": session(
        80, 24, "exec kak -n src/nested/notes.md",
        b":add-highlighter window/ regex '#[^\\n]*' 0:magenta\r",
        minimum=500, expect=("# Notes", "- one"), min_colors=5,
    ),
    "mc_menu": session(
        120, 35, "exec mc -u", key("F9"), key("DOWN"), minimum=1000,
        expect=("File listing", "Quick view", "Listing format"), min_colors=4,
    ),
    "mc_user_menu": session(
        120, 35, "exec mc -u", key("F2"), minimum=1000,
        expect=("User menu",), min_colors=4,
    ),
    "mc_quick_view_toggle": session(
        120, 35, "exec mc -u", b"\x13sample.py", b"\x18q", minimum=1000,
        expect=("def greet", "return f"), min_colors=4,
    ),
    "mc_view_python": session(
        120, 35, "exec mc -u", b"\x13sample.py", key("F3"), minimum=1000,
        expect=("def greet", "return f"), min_colors=3,
    ),
    "htop_setup": session(
        120, 35, "exec htop -d 10", key("F2"), minimum=1000,
        expect=("Setup", "Meters"), min_colors=5,
    ),
    "htop_search_dialog": session(
        120, 35, "exec htop -d 10", key("F3"), b"htop", minimum=1000,
        expect=("Search: htop",), min_colors=5,
    ),
    "htop_filter_dialog": session(
        120, 35, "exec htop -d 10", key("F4"), b"bash", minimum=1000,
        expect=("Filter: bash",), min_colors=5,
    ),
    "htop_signal_menu": session(
        120, 35, "exec htop -d 10", key("F9"), minimum=1000,
        expect=("Send signal", "SIGTERM"), min_colors=5,
    ),
}


def names():
    return tuple(SCENARIOS)
