#!/usr/bin/env python3
"""Generate direct musl providers for ABI-identical GLIBC imports.

Hard ABI cases remain explicit thunks in glibc_shim.c. This table only makes
the large, boring intersection between the selected Arch DSO closure and
musl's public archive visible to the custom resolver.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


UNSAFE_PREFIXES = (
    "pthread_",
    "sem_",
)
UNSAFE_NAMES = {
    "__tls_get_addr",
    "dladdr",
    "dlclose",
    "dlerror",
    "dlopen",
    "dlsym",
    "strerror_r",
}


def imported_glibc_symbols(root: Path) -> dict[str, set[str]]:
    result: dict[str, set[str]] = {}
    for path in sorted((root / "usr" / "lib").rglob("*")):
        if not path.is_file() or ".so" not in path.name:
            continue
        try:
            with path.open("rb") as source:
                magic = source.read(4)
            if magic != b"\x7fELF":
                continue
            output = subprocess.check_output(
                ["llvm-readelf", "--dyn-symbols", "--wide", str(path)],
                text=True,
                stderr=subprocess.DEVNULL,
            )
        except (OSError, subprocess.CalledProcessError):
            continue
        for line in output.splitlines():
            columns = line.split()
            if len(columns) < 8 or columns[6] != "UND":
                continue
            symbol = columns[7]
            if "@GLIBC_" in symbol:
                result.setdefault(symbol.split("@", 1)[0], set()).add(columns[3])
    return result


def musl_symbols(archive: Path) -> set[str]:
    output = subprocess.check_output(
        ["llvm-nm", "--defined-only", "--extern-only", str(archive)],
        text=True,
        stderr=subprocess.DEVNULL,
    )
    result: set[str] = set()
    for line in output.splitlines():
        match = re.match(r"^[0-9a-fA-F]+\s+[A-Za-z]\s+(.+)$", line)
        if match:
            result.add(match.group(1))
    return result


def main() -> None:
    if len(sys.argv) != 4:
        raise SystemExit("usage: generate_host_symbols.py ARCH_ROOT MUSL_LIBC_A OUTPUT_C")
    arch_root = Path(sys.argv[1])
    musl_archive = Path(sys.argv[2])
    output_path = Path(sys.argv[3])

    imported = imported_glibc_symbols(arch_root)
    available = musl_symbols(musl_archive)
    direct = sorted(
        symbol for symbol in imported.keys() & available
        if symbol not in UNSAFE_NAMES
        and not symbol.startswith(UNSAFE_PREFIXES)
    )

    lines = [
        "/* Generated by generate_host_symbols.py. */",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        "typedef struct { const char *name; void *address; } ShHostSymbol;",
        "__attribute__((noreturn)) void sh_glibc_unimplemented(const char *name);",
    ]
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'extern unsigned char sh_host_{index}[] __asm__("{escaped}");')
    lines.extend(["", "static const ShHostSymbol sh_host_symbols[] = {"])
    for index, symbol in enumerate(direct):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'    {{"{escaped}", (void *)(uintptr_t)sh_host_{index}}},')
    lines.extend([
        "};",
        "",
        "void *sh_host_resolve(const char *name) {",
        "    for (size_t index = 0;",
        "         index < sizeof(sh_host_symbols) / sizeof(sh_host_symbols[0]);",
        "         ++index) {",
        "        if (strcmp(name, sh_host_symbols[index].name) == 0)",
        "            return sh_host_symbols[index].address;",
        "    }",
        "    return NULL;",
        "}",
        "",
    ])
    traps = sorted(
        symbol for symbol, types in imported.items()
        if symbol not in direct and "OBJECT" not in types
    )
    for index, symbol in enumerate(traps):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.extend([
            f"__attribute__((noreturn)) static void sh_trap_{index}(void) {{",
            f'    sh_glibc_unimplemented("{escaped}");',
            "}",
        ])
    lines.extend(["", "static const ShHostSymbol sh_trap_symbols[] = {"])
    for index, symbol in enumerate(traps):
        escaped = symbol.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'    {{"{escaped}", (void *)(uintptr_t)sh_trap_{index}}},')
    lines.extend([
        "};",
        "",
        "void *sh_trap_resolve(const char *name) {",
        "    for (size_t index = 0;",
        "         index < sizeof(sh_trap_symbols) / sizeof(sh_trap_symbols[0]);",
        "         ++index) {",
        "        if (strcmp(name, sh_trap_symbols[index].name) == 0)",
        "            return sh_trap_symbols[index].address;",
        "    }",
        "    return NULL;",
        "}",
        "",
    ])
    output_path.write_text("\n".join(lines))
    print(f"generated {len(direct)} direct musl providers and {len(traps)} traps "
          f"in {output_path}")


if __name__ == "__main__":
    main()
